import Head from 'next/head'
// import { Inter } from 'next/font/google'
import styled from 'styled-components'
import React, {useState, useEffect} from 'react';
import { signIn, signInWithEmail } from "../utils/firebase"
import { SocialIcon } from "react-social-icons"
import Router from 'next/router'
import { useSelector } from "react-redux";

// const inter = Inter({ subsets: ['latin'] })

const Container = styled.div`
  maring: auto;
  text-align: center;
  padding: 1em;
  * {
    display: flex;
  }
`

const Login = styled.div`
  cursor: pointer;
  padding: 0.2em 0;
`

export default function Home() {
  // const { user } = useSelector((state) => state);
  // console.log(user)
  const [email, setEmail] = useState(null)
  const [password, setPassword] = useState(null)
  useEffect(() => {
    if (localStorage.getItem("name") && localStorage.getItem("email")) {
      // Router.push("/report")
      // window.location.href = "https://firebase.google.com/"
    }
    // console.log(password)
  }, [email, password])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Login>Sign In</Login>
        <Login><SocialIcon onClick={() => signIn("facebook")} network="facebook"/></Login>
        <Login><SocialIcon onClick={() => signIn("google")} network="google"/></Login>
        <br/>
        <div>
          <label>Email : </label>
          <input type="email" onChange={(e) => setEmail(e.target.value)}/>
        </div>
        <br/>
        <div>
          <label>Password : </label>
          <input type="password" onChange={(e) => setPassword(e.target.value)}/>
        </div>
        <br/>
        <button onClick={() => signInWithEmail(email, password)} >Sign in with email</button>
        {/* <Login><SocialIcon onClick={() => signInWithEmail(email, password)} network="email"/> Login with email</Login> */}
      </Container>
    </>
  )
}
